pipeline:
    stages:
        - stage:
              variables:
                  - name: HARNESS_API_KEY
                    type: Secret
                    value: harness_api_key
                  - name: HARNESS_ACCOUNT_ID
                    type: Secret
                    value: org.harness_account_id
                  - name: GOPATH
                    type: String
                    value: /goroot
                  - name: TF_ACC
                    type: String
                    value: "1"
                  - name: HARNESS_NG_API_KEY
                    type: Secret
                    value: harness_ng_api_key
                  - name: HARNESS_TEST_AWS_ACCESS_KEY_ID
                    type: Secret
                    value: org.aws_access_key_id
                  - name: HARNESS_TEST_AWS_SECRET_ACCESS_KEY
                    type: Secret
                    value: org.aws_secret_access_key
                  - name: HARNESS_TEST_AZURE_CLIENT_ID
                    type: Secret
                    value: org.azure_client_id
                  - name: HARNESS_TEST_AZURE_CLIENT_SECRET
                    type: Secret
                    value: org.azure_client_secret
                  - name: HARNESS_TEST_AZURE_TENANT_ID
                    type: Secret
                    value: org.azure_tenant_id
                  - name: HARNESS_TEST_SPOT_ACCT_ID
                    type: Secret
                    value: org.spotinst_account_id
                  - name: HARNESS_TEST_SPOT_TOKEN
                    type: Secret
                    value: org.spotinst_token
                  - name: HARNESS_DELEGATE_SECRET
                    type: Secret
                    value: org.harness_delegate_secret
                  - name: HARNESS_TEST_DELEGATE_WAIT_TIMEOUT
                    type: String
                    value: 10m
                  - name: TEST_TIMEOUT
                    type: String
                    value: 120m
              type: CI
              spec:
                  sharedPaths:
                      - /goroot
                      - /var/run
                      - /var/lib/docker
                  serviceDependencies:
                      - type: Service
                        spec:
                            resources:
                                limits:
                                    memory: 8Gi
                                    cpu: "2"
                            privileged: true
                            image: docker:dind
                            connectorRef: account.harnessImage
                        name: DockerHost
                        identifier: DockerHost
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    privileged: false
                                    image: docker:dind
                                    connectorRef: account.harnessImage
                                    command: |-
                                        ls -la /var/run
                                        ls -la /var/lib/docker

                                        while ! docker ps ;do
                                            echo "Docker not availble yet"
                                            sleep 1s
                                        done
                                            echo "Docker Service Ready"

                                        ls -la /var/run
                                        ls -la /var/lib/docker
                                name: Wait for Docker Host
                                identifier: Wait_for_Docker_Host
                          - step:
                                type: RestoreCacheGCS
                                spec:
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                                    key: terraform-provider-harness-{{ checksum "go.mod" }}
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    archiveFormat: Gzip
                                name: Restore from cache
                                identifier: Restore_from_cache
                          - step:
                                type: Run
                                spec:
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                                    privileged: false
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    connectorRef: org.gcp
                                    command: go mod vendor
                                name: Install Dependencies
                                identifier: installdependencies
                          - step:
                                type: SaveCacheGCS
                                spec:
                                    sourcePaths:
                                        - ./vendor
                                    key: terraform-provider-harness-{{ checksum "go.mod" }}
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    archiveFormat: Gzip
                                name: Save cache
                                identifier: Save_cache
                          - step:
                                type: Run
                                spec:
                                    resources:
                                        limits:
                                            memory: 4Gi
                                            cpu: "1"
                                    privileged: false
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    connectorRef: org.gcp
                                    command: go build -v
                                name: Build
                                identifier: build
                          - parallel:
                                - step:
                                      type: Run
                                      spec:
                                          resources:
                                              limits:
                                                  memory: 2Gi
                                                  cpu: "1"
                                          privileged: false
                                          image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-10
                                          connectorRef: org.gcp
                                          command: golangci-lint run -v --timeout=10m
                                      name: Lint
                                      identifier: lint
                                      failureStrategies:
                                          - onFailure:
                                                errors:
                                                    - AllErrors
                                                action:
                                                    type: Ignore
                                - step:
                                      type: Run
                                      timeout: <+build.variables.TEST_TIMEOUT>
                                      spec:
                                          connectorRef: org.gcp
                                          image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                          command: gotestsum --junitfile junit.xml --format testname ./... -timeout <+build.variables.TEST_TIMEOUT>  -- -cover
                                          privileged: false
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - junit.xml
                                          envVariables:
                                              TF_ACC_TERRAFORM_VERSION: 1.0.0
                                              TF_ACC: "1"
                                          resources:
                                              limits:
                                                  memory: 6Gi
                                                  cpu: "2"
                                      name: Test Terraform v1-0-0
                                      identifier: Test_Terraform_v100
                                      failureStrategies:
                                          - onFailure:
                                                errors:
                                                    - AllErrors
                                                action:
                                                    type: Ignore
                  cloneCodebase: true
              name: Build
              identifier: build
    properties:
        ci:
            codebase:
                repoName: terraform-provider-harness
                connectorRef: org.githubharnessio
                build: <+input>
    projectIdentifier: tf_provider
    orgIdentifier: Micahs_Projects
    name: ci
    identifier: ci
    description: CI build
