/*
 * Infrastructure as Code Management
 *
 * Services for Harness IaCM Module.
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type IacmPolicy struct {
	// Harness account ID associated with this policy
	AccountId string `json:"account_id"`
	// Time the policy was created
	Created int64 `json:"created"`
	// identifier of the policy
	Identifier string `json:"identifier"`
	// Name of the policy
	Name string `json:"name"`
	// Harness organization ID associated with this policy
	OrgId string `json:"org_id"`
	// Harness project ID associated with this policy
	ProjectId string `json:"project_id"`
	// Rego that defines the policy
	Rego string `json:"rego"`
	// Time the policy was last updated
	Updated int64 `json:"updated"`
}
