/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type EntityInfo struct {
	Field                 string `json:"field,omitempty"`
	ClusterName           string `json:"clusterName,omitempty"`
	ClusterId             string `json:"clusterId,omitempty"`
	Namespace             string `json:"namespace,omitempty"`
	WorkloadName          string `json:"workloadName,omitempty"`
	WorkloadType          string `json:"workloadType,omitempty"`
	GcpProjectId          string `json:"gcpProjectId,omitempty"`
	GcpProduct            string `json:"gcpProduct,omitempty"`
	GcpSKUId              string `json:"gcpSKUId,omitempty"`
	GcpSKUDescription     string `json:"gcpSKUDescription,omitempty"`
	AwsUsageAccountId     string `json:"awsUsageAccountId,omitempty"`
	AwsServiceCode        string `json:"awsServiceCode,omitempty"`
	AwsInstancetype       string `json:"awsInstancetype,omitempty"`
	AwsUsageType          string `json:"awsUsageType,omitempty"`
	AzureSubscriptionGuid string `json:"azureSubscriptionGuid,omitempty"`
	AzureServiceName      string `json:"azureServiceName,omitempty"`
	AzureInstanceId       string `json:"azureInstanceId,omitempty"`
}
