/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// A list of Target Groups (Segments)
type Segments struct {
	// The total number of items
	ItemCount int32 `json:"itemCount"`
	// The total number of pages
	PageCount int32 `json:"pageCount"`
	// The current page
	PageIndex int32 `json:"pageIndex"`
	// The number of items per page
	PageSize int32 `json:"pageSize"`
	// The version of this object.  The version will be incremented each time the object is modified
	Version  int32     `json:"version,omitempty"`
	Segments []Segment `json:"segments,omitempty"`
}
