/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type ContainerRecommendation struct {
	Current           *ResourceRequirement           `json:"current,omitempty"`
	Burstable         *ResourceRequirement           `json:"burstable,omitempty"`
	Guaranteed        *ResourceRequirement           `json:"guaranteed,omitempty"`
	Recommended       *ResourceRequirement           `json:"recommended,omitempty"`
	PercentileBased   map[string]ResourceRequirement `json:"percentileBased,omitempty"`
	LastDayCost       *Cost                          `json:"lastDayCost,omitempty"`
	NumDays           int32                          `json:"numDays,omitempty"`
	TotalSamplesCount int32                          `json:"totalSamplesCount,omitempty"`
}
