/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Notification Management Service
 *
 * API version: 1.0
 * Contact: contact.harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type NotificationsSimulateDto struct {
	Count      int32  `json:"count,omitempty"`
	AccountId  string `json:"accountId,omitempty"`
	OrgId      string `json:"orgId,omitempty"`
	ProjectId  string `json:"projectId,omitempty"`
	PipelineId string `json:"pipelineId,omitempty"`
	Event      string `json:"event,omitempty"`
}
