/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Contains information of Resource Group
type ResourcegroupResourceGroup struct {
	AccountIdentifier  string             `json:"accountIdentifier"`
	OrgIdentifier      string             `json:"orgIdentifier,omitempty"`
	ProjectIdentifier  string             `json:"projectIdentifier,omitempty"`
	Identifier         string             `json:"identifier"`
	Name               string             `json:"name"`
	ResourceSelectors  []ResourceSelector `json:"resourceSelectors,omitempty"`
	FullScopeSelected  bool               `json:"fullScopeSelected,omitempty"`
	Tags               map[string]string  `json:"tags,omitempty"`
	Description        string             `json:"description,omitempty"`
	AllowedScopeLevels []string           `json:"allowedScopeLevels,omitempty"`
	Color              string             `json:"color,omitempty"`
	Scope              *Scope             `json:"scope,omitempty"`
}
