/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// A Target object
type Target struct {
	// The account ID that the target belongs to
	Account string `json:"account"`
	// Indicates if this target is anonymous
	Anonymous bool `json:"anonymous,omitempty"`
	// a JSON representation of the attributes for this target
	Attributes *interface{} `json:"attributes,omitempty"`
	// The date and time in milliseconds when this Target was created
	CreatedAt int64 `json:"createdAt,omitempty"`
	// The identifier for the environment that the target belongs to
	Environment string `json:"environment"`
	// The unique identifier for this target
	Identifier string `json:"identifier"`
	// The name of this Target
	Name string `json:"name"`
	// The identifier for the organization that the target belongs to
	Org string `json:"org"`
	// The identifier for the project that this target belongs to
	Project string `json:"project"`
	// A list of Target Groups (Segments) that this Target belongs to
	Segments []Segment `json:"segments,omitempty"`
}
