/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type RuntimeStreamError struct {
	GrpcCode   int32         `json:"grpc_code,omitempty"`
	HttpCode   int32         `json:"http_code,omitempty"`
	Message    string        `json:"message,omitempty"`
	HttpStatus string        `json:"http_status,omitempty"`
	Details    []ProtobufAny `json:"details,omitempty"`
}
