/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type GovernanceMetadata struct {
	UnknownFields             *UnknownFieldSet             `json:"unknownFields,omitempty"`
	Timestamp                 int64                        `json:"timestamp,omitempty"`
	Initialized               bool                         `json:"initialized,omitempty"`
	Action                    string                       `json:"action,omitempty"`
	Created                   int64                        `json:"created,omitempty"`
	Entity                    string                       `json:"entity,omitempty"`
	Status                    string                       `json:"status,omitempty"`
	AccountId                 string                       `json:"accountId,omitempty"`
	IdBytes                   *ByteString                  `json:"idBytes,omitempty"`
	DetailsList               []PolicySetMetadata          `json:"detailsList,omitempty"`
	DetailsOrBuilderList      []PolicySetMetadataOrBuilder `json:"detailsOrBuilderList,omitempty"`
	DetailsCount              int32                        `json:"detailsCount,omitempty"`
	EntityBytes               *ByteString                  `json:"entityBytes,omitempty"`
	ActionBytes               *ByteString                  `json:"actionBytes,omitempty"`
	OrgId                     string                       `json:"orgId,omitempty"`
	StatusBytes               *ByteString                  `json:"statusBytes,omitempty"`
	AccountIdBytes            *ByteString                  `json:"accountIdBytes,omitempty"`
	OrgIdBytes                *ByteString                  `json:"orgIdBytes,omitempty"`
	ProjectId                 string                       `json:"projectId,omitempty"`
	ProjectIdBytes            *ByteString                  `json:"projectIdBytes,omitempty"`
	TypeBytes                 *ByteString                  `json:"typeBytes,omitempty"`
	SerializedSize            int32                        `json:"serializedSize,omitempty"`
	MessageBytes              *ByteString                  `json:"messageBytes,omitempty"`
	Deny                      bool                         `json:"deny,omitempty"`
	ParserForType             *ParserGovernanceMetadata    `json:"parserForType,omitempty"`
	DefaultInstanceForType    *GovernanceMetadata          `json:"defaultInstanceForType,omitempty"`
	Message                   string                       `json:"message,omitempty"`
	Id                        string                       `json:"id,omitempty"`
	Type_                     string                       `json:"type,omitempty"`
	AllFields                 map[string]interface{}       `json:"allFields,omitempty"`
	InitializationErrorString string                       `json:"initializationErrorString,omitempty"`
	DescriptorForType         *Descriptor                  `json:"descriptorForType,omitempty"`
	MemoizedSerializedSize    int32                        `json:"memoizedSerializedSize,omitempty"`
}
