/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type ApplicationsResourceNetworkingInfo struct {
	TargetLabels map[string]string         `json:"targetLabels,omitempty"`
	TargetRefs   []ApplicationsResourceRef `json:"targetRefs,omitempty"`
	Labels       map[string]string         `json:"labels,omitempty"`
	Ingress      []V1LoadBalancerIngress   `json:"ingress,omitempty"`
	// ExternalURLs holds list of URLs which should be available externally. List is populated for ingress resources using rules hostnames.
	ExternalURLs []string `json:"externalURLs,omitempty"`
}
