/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Notification Management Service
 *
 * API version: 1.0
 * Contact: contact.harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Event and Template Configuration
type EventTemplateConfigurationDto struct {
	// List of notification events
	NotificationEvents []string                       `json:"notification_events"`
	Template           *CustomNotificationTemplateDto `json:"template"`
}
