/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// This has the details of Service Account in Harness.
type ServiceAccount struct {
	// Identifier of the Service Account.
	Identifier string `json:"identifier,omitempty"`
	// Name of the Service Account.
	Name string `json:"name,omitempty"`
	// Email of the Service Account.
	Email string `json:"email,omitempty"`
	// Description of the Service Account.
	Description string `json:"description,omitempty"`
	// Tags of the Service Account.
	Tags map[string]string `json:"tags,omitempty"`
	// Account Identifier for the Entity
	AccountIdentifier string `json:"accountIdentifier,omitempty"`
	// Organization Identifier for the Entity
	OrgIdentifier string `json:"orgIdentifier,omitempty"`
	// Project Identifier for the Entity
	ProjectIdentifier string `json:"projectIdentifier,omitempty"`
}
