/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type ExecutableResponse struct {
	UnknownFields             *UnknownFieldSet                       `json:"unknownFields,omitempty"`
	SerializedSize            int32                                  `json:"serializedSize,omitempty"`
	ParserForType             *ParserExecutableResponse              `json:"parserForType,omitempty"`
	DefaultInstanceForType    *ExecutableResponse                    `json:"defaultInstanceForType,omitempty"`
	Initialized               bool                                   `json:"initialized,omitempty"`
	Task                      *TaskExecutableResponse                `json:"task,omitempty"`
	Sync                      *SyncExecutableResponse                `json:"sync,omitempty"`
	Child                     *ChildExecutableResponse               `json:"child,omitempty"`
	Async                     *AsyncExecutableResponse               `json:"async,omitempty"`
	ResponseCase              string                                 `json:"responseCase,omitempty"`
	AsyncOrBuilder            *AsyncExecutableResponseOrBuilder      `json:"asyncOrBuilder,omitempty"`
	ChildOrBuilder            *ChildExecutableResponseOrBuilder      `json:"childOrBuilder,omitempty"`
	Children                  *ChildrenExecutableResponse            `json:"children,omitempty"`
	ChildrenOrBuilder         *ChildrenExecutableResponseOrBuilder   `json:"childrenOrBuilder,omitempty"`
	ChildChain                *ChildChainExecutableResponse          `json:"childChain,omitempty"`
	ChildChainOrBuilder       *ChildChainExecutableResponseOrBuilder `json:"childChainOrBuilder,omitempty"`
	TaskOrBuilder             *TaskExecutableResponseOrBuilder       `json:"taskOrBuilder,omitempty"`
	TaskChain                 *TaskChainExecutableResponse           `json:"taskChain,omitempty"`
	TaskChainOrBuilder        *TaskChainExecutableResponseOrBuilder  `json:"taskChainOrBuilder,omitempty"`
	SyncOrBuilder             *SyncExecutableResponseOrBuilder       `json:"syncOrBuilder,omitempty"`
	SkipTask                  *SkipTaskExecutableResponse            `json:"skipTask,omitempty"`
	SkipTaskOrBuilder         *SkipTaskExecutableResponseOrBuilder   `json:"skipTaskOrBuilder,omitempty"`
	InitializationErrorString string                                 `json:"initializationErrorString,omitempty"`
	DescriptorForType         *Descriptor                            `json:"descriptorForType,omitempty"`
	AllFields                 map[string]interface{}                 `json:"allFields,omitempty"`
	MemoizedSerializedSize    int32                                  `json:"memoizedSerializedSize,omitempty"`
}
