/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// This is the Environment Group Entity defined in Harness
type EnvironmentGroupResponse struct {
	// Account Identifier for the Entity.
	AccountId string `json:"accountId,omitempty"`
	// Organization Identifier for the Entity.
	OrgIdentifier string `json:"orgIdentifier,omitempty"`
	// Project Identifier for the Entity.
	ProjectIdentifier string `json:"projectIdentifier,omitempty"`
	// Identifier for the Entity.
	Identifier string `json:"identifier,omitempty"`
	// Name of the Entity
	Name string `json:"name,omitempty"`
	// Description of the entity
	Description string `json:"description,omitempty"`
	// Color Code for the Entity
	Color string `json:"color,omitempty"`
	// Deletion status for Entity
	Deleted bool `json:"deleted,omitempty"`
	// Tags
	Tags map[string]string `json:"tags,omitempty"`
	// Environment Identifiers linked with Environment Group Identity
	EnvIdentifiers []string `json:"envIdentifiers,omitempty"`
	// Info of Environments linked with Entity
	EnvResponse []EnvironmentResponse `json:"envResponse,omitempty"`
	GitDetails  *EntityGitDetails     `json:"gitDetails,omitempty"`
	// Yaml of the Entity
	Yaml string `json:"yaml,omitempty"`
}
