/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Overview of the cost.
type CostOverview struct {
	StatsLabel       string `json:"statsLabel,omitempty"`
	StatsDescription string `json:"statsDescription,omitempty"`
	StatsValue       string `json:"statsValue,omitempty"`
	// Cost trend
	Trend float64 `json:"Trend,omitempty"`
	// Total cost
	Cost float64 `json:"Cost,omitempty"`
}
