/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Filters return values as per the field, operator & List of string values provided
type FieldFilter struct {
	// List of all possible Fields
	Field string `json:"field,omitempty"`
	// List of all possible Operators
	Operator string `json:"operator,omitempty"`
	// List of all values of the filter.
	Values []string `json:"Values,omitempty"`
}
