/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// This has scope details for the resource defined in Harness.
type AuditResourceScope struct {
	// Identifier of Account
	AccountIdentifier string `json:"accountIdentifier,omitempty"`
	// Identifier of Organization
	OrgIdentifier string `json:"orgIdentifier,omitempty"`
	// Identifier of Project
	ProjectIdentifier string `json:"projectIdentifier,omitempty"`
	// Additional information about the Resource Scope
	Labels map[string]string `json:"labels,omitempty"`
}
