/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type ScimUser struct {
	Schemas     []string  `json:"schemas,omitempty"`
	UserName    string    `json:"userName,omitempty"`
	DisplayName string    `json:"displayName,omitempty"`
	Active      bool      `json:"active,omitempty"`
	Emails      *JsonNode `json:"emails,omitempty"`
	Roles       *JsonNode `json:"roles,omitempty"`
	Name        *JsonNode `json:"name,omitempty"`
	Groups      *JsonNode `json:"groups,omitempty"`
	Password    *JsonNode `json:"password,omitempty"`
	Id          string    `json:"id,omitempty"`
	ExternalId  string    `json:"externalId,omitempty"`
	Meta        *JsonNode `json:"meta,omitempty"`
}
