/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type RoleAssignmentMetadataDto struct {
	Identifier string `json:"identifier,omitempty"`
	RoleIdentifier string `json:"roleIdentifier,omitempty"`
	RoleName string `json:"roleName,omitempty"`
	ResourceGroupIdentifier string `json:"resourceGroupIdentifier,omitempty"`
	ResourceGroupName string `json:"resourceGroupName,omitempty"`
	ManagedRole bool `json:"managedRole,omitempty"`
	ManagedRoleAssignment bool `json:"managedRoleAssignment,omitempty"`
}
