/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Perspective ID to name mapping
type Perspective struct {
	Id            string  `json:"id,omitempty"`
	Name          string  `json:"name,omitempty"`
	TotalCost     float64 `json:"totalCost,omitempty"`
	CreatedBy     string  `json:"createdBy,omitempty"`
	CreatedAt     int64   `json:"createdAt,omitempty"`
	LastUpdatedAt int64   `json:"lastUpdatedAt,omitempty"`
	// Perspective chart type
	ChartType string         `json:"chartType,omitempty"`
	ViewType  string         `json:"viewType,omitempty"`
	ViewState string         `json:"viewState,omitempty"`
	GroupBy   *QlceViewField `json:"groupBy,omitempty"`
	// The type of Perspective time range filter, select CUSTOM is you want a Perspective between a fixed set of startTime and endTime
	TimeRange                   string   `json:"timeRange,omitempty"`
	DataSources                 []string `json:"dataSources,omitempty"`
	IsReportScheduledConfigured bool     `json:"isReportScheduledConfigured,omitempty"`
	ReportScheduledConfigured   bool     `json:"reportScheduledConfigured,omitempty"`
}
