/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type FreezeFilterPropertiesDto struct {
	FreezeIdentifiers []string `json:"freezeIdentifiers,omitempty"`
	Sort              []string `json:"sort,omitempty"`
	FreezeStatus      string   `json:"freezeStatus,omitempty"`
	StartTime         int64    `json:"startTime,omitempty"`
	EndTime           int64    `json:"endTime,omitempty"`
	SearchTerm        string   `json:"searchTerm,omitempty"`
}
