/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// A Target Group (Segment) response
type Segment struct {
	// The data and time in milliseconds when the group was created
	CreatedAt int64 `json:"createdAt,omitempty"`
	// The environment this target group belongs to
	Environment string `json:"environment,omitempty"`
	// A list of Targets who are excluded from this target group
	Excluded []Target `json:"excluded,omitempty"`
	// Unique identifier for the target group.
	Identifier string `json:"identifier"`
	// A list of Targets who belong to this target group
	Included []Target `json:"included,omitempty"`
	// The data and time in milliseconds when the group was last modified
	ModifiedAt int64 `json:"modifiedAt,omitempty"`
	// Name of the target group.
	Name string `json:"name"`
	// An array of rules that can cause a user to be included in this segment.
	Rules []Clause `json:"rules,omitempty"`
	// Tags for this target group
	Tags []Tag `json:"tags,omitempty"`
	// The version of this group.  Each time it is modified the version is incremented
	Version int64 `json:"version,omitempty"`
}
