/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// This has details of the Organization as defined in Harness.
type Organization struct {
	// Identifier of the Organization
	Identifier string `json:"identifier,omitempty"`
	// Name of the Organization
	Name string `json:"name,omitempty"`
	// Description of the Organization.
	Description string `json:"description,omitempty"`
	// Tags for the Organization.
	Tags map[string]string `json:"tags,omitempty"`
}
