/*
 * Infrastructure as Code Management
 *
 * Services for Harness IaCM Module.
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Variable is the representation for a single variable associated with a Variable Set.
type VariableSetVar struct {
	// Timestamp when the variable set was created.
	Created int64 `json:"created,omitempty"`
	// ID PK for internal uses
	Id int64 `json:"id,omitempty"`
	// Key is the identifier for the secret.
	Key string `json:"key"`
	// Timestamp when the variable set was last updated.
	Updated int64 `json:"updated,omitempty"`
	// Value is the value of the secret.
	Value string `json:"value"`
	// Type indecates the value type of the secret. In the case of secret this is a reference to an item in the secret store
	ValueType string `json:"value_type"`
}
