/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type VaultConnectorDto struct {
	AuthToken string `json:"authToken,omitempty"`
	BasePath string `json:"basePath,omitempty"`
	VaultUrl string `json:"vaultUrl,omitempty"`
	IsReadOnly bool `json:"isReadOnly,omitempty"`
	RenewalIntervalMinutes int64 `json:"renewalIntervalMinutes,omitempty"`
	SecretEngineManuallyConfigured bool `json:"secretEngineManuallyConfigured,omitempty"`
	SecretEngineName string `json:"secretEngineName,omitempty"`
	AppRoleId string `json:"appRoleId,omitempty"`
	SecretId string `json:"secretId,omitempty"`
	IsDefault bool `json:"isDefault,omitempty"`
	SecretEngineVersion int32 `json:"secretEngineVersion,omitempty"`
	DelegateSelectors []string `json:"delegateSelectors,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	SinkPath string `json:"sinkPath,omitempty"`
	UseVaultAgent bool `json:"useVaultAgent,omitempty"`
	Default_ bool `json:"default,omitempty"`
	AccessType string `json:"accessType,omitempty"`
	ReadOnly bool `json:"readOnly,omitempty"`
}
