/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type ApplicationSetQueryApplicationSetSortByOptions string

// List of ApplicationSetQueryApplicationSetSortByOptions
const (
	SORT_BY_NOT_SET_ApplicationSetQueryApplicationSetSortByOptions ApplicationSetQueryApplicationSetSortByOptions = "SORT_BY_NOT_SET"
	NAME_ApplicationSetQueryApplicationSetSortByOptions            ApplicationSetQueryApplicationSetSortByOptions = "NAME"
	GITOPS_AGENT_ApplicationSetQueryApplicationSetSortByOptions    ApplicationSetQueryApplicationSetSortByOptions = "GITOPS_AGENT"
	SOURCE_ApplicationSetQueryApplicationSetSortByOptions          ApplicationSetQueryApplicationSetSortByOptions = "SOURCE"
	DESTINATION_ApplicationSetQueryApplicationSetSortByOptions     ApplicationSetQueryApplicationSetSortByOptions = "DESTINATION"
)
