/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// This object contains the Anomalies associated with a perspective
type PerspectiveAnomalyData struct {
	Timestamp                  int64        `json:"timestamp,omitempty"`
	AnomalyCount               int32        `json:"anomalyCount,omitempty"`
	ActualCost                 float64      `json:"actualCost,omitempty"`
	DifferenceFromExpectedCost float64      `json:"differenceFromExpectedCost,omitempty"`
	AssociatedResources        []EntityInfo `json:"associatedResources,omitempty"`
	ResourceType               string       `json:"resourceType,omitempty"`
}
