/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

import "encoding/json"

type ServiceLevelIndicatorDto struct {
	Name       string                                 `json:"name,omitempty"`
	Identifier string                                 `json:"identifier,omitempty"`
	Type_      SLIEvaluationType                      `json:"type,omitempty"`
	Window     *WindowBasedServiceLevelIndicatorSpec  `json:"-"`
	Request    *RequestBasedServiceLevelIndicatorSpec `json:"-"`
	MetricLess *MetricLessServiceLevelIndicatorSpec   `json:"-"`

	Spec json.RawMessage `json:"spec"`
}
