/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type ManualIssuer struct {
	UnknownFields             *UnknownFieldSet       `json:"unknownFields,omitempty"`
	UserId                    string                 `json:"userId,omitempty"`
	TypeBytes                 *ByteString            `json:"typeBytes,omitempty"`
	SerializedSize            int32                  `json:"serializedSize,omitempty"`
	ParserForType             *ParserManualIssuer    `json:"parserForType,omitempty"`
	DefaultInstanceForType    *ManualIssuer          `json:"defaultInstanceForType,omitempty"`
	IdentifierBytes           *ByteString            `json:"identifierBytes,omitempty"`
	Initialized               bool                   `json:"initialized,omitempty"`
	Type_                     string                 `json:"type,omitempty"`
	EmailIdBytes              *ByteString            `json:"emailIdBytes,omitempty"`
	UserIdBytes               *ByteString            `json:"userIdBytes,omitempty"`
	EmailId                   string                 `json:"emailId,omitempty"`
	Identifier                string                 `json:"identifier,omitempty"`
	InitializationErrorString string                 `json:"initializationErrorString,omitempty"`
	DescriptorForType         *Descriptor            `json:"descriptorForType,omitempty"`
	AllFields                 map[string]interface{} `json:"allFields,omitempty"`
	MemoizedSerializedSize    int32                  `json:"memoizedSerializedSize,omitempty"`
}
