/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type Pageable struct {
	Sort *Sort `json:"sort,omitempty"`
	PageSize int32 `json:"pageSize,omitempty"`
	Paged bool `json:"paged,omitempty"`
	Unpaged bool `json:"unpaged,omitempty"`
	PageNumber int32 `json:"pageNumber,omitempty"`
	Offset int64 `json:"offset,omitempty"`
}
