# Visit https://goreleaser.com for documentation on customization
before:
  hooks:
    # Ensure modules are tidy and compatible with Go 1.23.0
    - go mod tidy -compat=1.23

builds:
  - env:
      # Disable CGO for compatibility with CI/CD systems like Terraform Cloud
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
# Set draft to true if you want to manually review before publishing
# draft: true

changelog:
  skip: false
  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo
