/*
 * Harness Artifact Registry API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package har

// Docker Artifact Version Summary
type ArtifactVersionSummary struct {
	ImageName            string       `json:"imageName"`
	IsLatestVersion      bool         `json:"isLatestVersion,omitempty"`
	PackageType          *PackageType `json:"packageType"`
	SscaArtifactId       string       `json:"sscaArtifactId,omitempty"`
	SscaArtifactSourceId string       `json:"sscaArtifactSourceId,omitempty"`
	StoExecutionId       string       `json:"stoExecutionId,omitempty"`
	StoPipelineId        string       `json:"stoPipelineId,omitempty"`
	Version              string       `json:"version"`
}
