/*
 * Harness Artifact Registry API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package har

type InlineResponse20017 struct {
	Data *ListRegistryArtifact `json:"data"`
	Status *Status `json:"status"`
}
