/*
 * Harness Artifact Registry API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package har

type BuildDetails struct {
	OrgIdentifier       string `json:"orgIdentifier,omitempty"`
	PipelineDisplayName string `json:"pipelineDisplayName,omitempty"`
	PipelineExecutionId string `json:"pipelineExecutionId,omitempty"`
	PipelineIdentifier  string `json:"pipelineIdentifier,omitempty"`
	ProjectIdentifier   string `json:"projectIdentifier,omitempty"`
	StageExecutionId    string `json:"stageExecutionId,omitempty"`
	StepExecutionId     string `json:"stepExecutionId,omitempty"`
}
