/*
 * Harness Artifact Registry API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package har

type ReplicationRuleRequest struct {
	AllowedPatterns []string `json:"allowedPatterns"`
	BlockedPatterns []string `json:"blockedPatterns"`
	Destination *ReplicationRegistry `json:"destination"`
	DestinationType string `json:"destinationType"`
	Source *ReplicationRegistry `json:"source"`
	SourceType string `json:"sourceType"`
}
