/*
 * Harness Artifact Registry API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package har

// Artifact Detail
type ArtifactDetail struct {
	CreatedAt string `json:"createdAt,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	DownloadCount int64 `json:"downloadCount,omitempty"`
	ModifiedAt string `json:"modifiedAt,omitempty"`
	Name string `json:"name,omitempty"`
	PackageType *PackageType `json:"packageType"`
	Size string `json:"size,omitempty"`
	Version string `json:"version"`
}
