/*
 * Harness Artifact Registry API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package har

type OneOfArtifactDetail struct {
    DockerArtifactDetailConfig
    HelmArtifactDetailConfig
    GenericArtifactDetailConfig
    MavenArtifactDetailConfig
    PythonArtifactDetailConfig
    NpmArtifactDetailConfig
    RpmArtifactDetailConfig
    NugetArtifactDetailConfig
    CargoArtifactDetailConfig
}
