/*
 * Harness Artifact Registry API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package har

// A list of replication rules
type ListReplicationRule struct {
	// The total number of items
	ItemCount int64 `json:"itemCount"`
	// The total number of pages
	PageCount int64 `json:"pageCount"`
	// The current page
	PageIndex int64 `json:"pageIndex"`
	// The number of items per page
	PageSize int32 `json:"pageSize"`
	// A list of Replication Rules
	Rules []ReplicationRule `json:"rules"`
}
