package fme

import (
	"context"

	"github.com/harness/terraform-provider-harness/helpers"
	"github.com/harness/terraform-provider-harness/internal"
	"github.com/harness/terraform-provider-harness/internal/service/platform/fme/api"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func ResourceFMEEnvironment() *schema.Resource {
	return &schema.Resource{
		Description:   "Resource for creating a FME (Feature Management Engine) environment.",
		ReadContext:   resourceFMEEnvironmentRead,
		CreateContext: resourceFMEEnvironmentCreate,
		UpdateContext: resourceFMEEnvironmentUpdate,
		DeleteContext: resourceFMEEnvironmentDelete,
		Importer:      helpers.MultiLevelResourceImporter,

		Schema: map[string]*schema.Schema{
			"id": {
				Description: "Unique identifier of the environment.",
				Type:        schema.TypeString,
				Computed:    true,
			},
			"workspace_id": {
				Description:  "Unique identifier of the workspace.",
				Type:         schema.TypeString,
				Required:     true,
				ForceNew:     true,
				ValidateFunc: validation.IsUUID,
			},
			"name": {
				Description:  "Name of the environment.",
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringIsNotEmpty,
			},
			"production": {
				Description: "Whether this is a production environment.",
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     false,
			},
			"remove_environment_from_state_only": {
				Description: "If true, the environment will only be removed from Terraform state and not deleted from the API.",
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     false,
			},
			"api_tokens": {
				Description: "Automatically created API tokens for this environment. These are generated by Split.io when the environment is created.",
				Type:        schema.TypeList,
				Computed:    true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Description: "Unique identifier of the API token.",
							Type:        schema.TypeString,
							Computed:    true,
						},
						"name": {
							Description: "Name of the API token.",
							Type:        schema.TypeString,
							Computed:    true,
						},
						"type": {
							Description: "Type of the API token.",
							Type:        schema.TypeString,
							Computed:    true,
						},
						"api_key_type": {
							Description: "API key type (e.g., 'server-side', 'client-side').",
							Type:        schema.TypeString,
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func resourceFMEEnvironmentCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	session := meta.(*internal.Session)
	fmeClient := session.FMEClient

	if fmeClient == nil {
		return diag.Errorf("FME client not configured")
	}

	c := fmeClient.(*FMEConfig)

	workspaceID := d.Get("workspace_id").(string)
	name := d.Get("name").(string)
	production := d.Get("production").(bool)

	req := &api.EnvironmentRequest{
		Name:       &name,
		Production: &production,
	}

	env, err := c.APIClient.Environments.Create(workspaceID, req)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(*env.ID)

	// Store API tokens from create response (they are only returned on create)
	if len(env.ApiTokens) > 0 {
		if err := d.Set("api_tokens", flattenApiTokens(env.ApiTokens)); err != nil {
			return diag.FromErr(err)
		}
	}

	// Don't call read here as it won't return the API tokens
	d.Set("name", env.Name)
	d.Set("production", env.Production)

	return nil
}

func resourceFMEEnvironmentRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	session := meta.(*internal.Session)
	fmeClient := session.FMEClient

	if fmeClient == nil {
		return diag.Errorf("FME client not configured")
	}

	c := fmeClient.(*FMEConfig)

	workspaceID := d.Get("workspace_id").(string)
	env, err := c.APIClient.Environments.Get(workspaceID, d.Id())
	if err != nil {
		return diag.FromErr(err)
	}

	if env == nil {
		d.SetId("")
		return nil
	}

	d.Set("name", env.Name)
	d.Set("production", env.Production)

	return nil
}

func resourceFMEEnvironmentUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	session := meta.(*internal.Session)
	fmeClient := session.FMEClient

	if fmeClient == nil {
		return diag.Errorf("FME client not configured")
	}

	c := fmeClient.(*FMEConfig)

	req := &api.EnvironmentRequest{}

	if d.HasChange("name") {
		name := d.Get("name").(string)
		req.Name = &name
	}

	if d.HasChange("production") {
		production := d.Get("production").(bool)
		req.Production = &production
	}

	workspaceID := d.Get("workspace_id").(string)
	_, err := c.APIClient.Environments.Update(workspaceID, d.Id(), req)
	if err != nil {
		return diag.FromErr(err)
	}

	return resourceFMEEnvironmentRead(ctx, d, meta)
}

func resourceFMEEnvironmentDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	session := meta.(*internal.Session)
	fmeClient := session.FMEClient

	if fmeClient == nil {
		return diag.Errorf("FME client not configured")
	}

	c := fmeClient.(*FMEConfig)

	// Check if we should only remove from state without calling API delete
	removeFromStateOnly := d.Get("remove_environment_from_state_only").(bool)

	if !removeFromStateOnly {
		// First, delete any API tokens associated with this environment
		// The Split.io API requires all API tokens to be deleted before an environment can be deleted
		if apiTokens, ok := d.GetOk("api_tokens"); ok {
			tokensList := apiTokens.([]interface{})
			for _, tokenRaw := range tokensList {
				token := tokenRaw.(map[string]interface{})
				if tokenID, ok := token["id"].(string); ok && tokenID != "" {
					err := c.APIClient.ApiKeys.Delete(tokenID)
					if err != nil {
						// Log the error but continue trying to delete other tokens
						// Some tokens may have already been deleted manually
						diag.FromErr(err)
					}
				}
			}
		}

		// Now delete the environment
		workspaceID := d.Get("workspace_id").(string)
		err := c.APIClient.Environments.Delete(workspaceID, d.Id())
		if err != nil {
			return diag.FromErr(err)
		}
	}

	// Always clear the ID from state regardless of the option
	d.SetId("")
	return nil
}

// flattenApiTokens converts API tokens from the API response to a format suitable for Terraform state
func flattenApiTokens(tokens []api.ApiToken) []interface{} {
	result := make([]interface{}, len(tokens))
	for i, token := range tokens {
		m := map[string]interface{}{}
		if token.ID != nil {
			m["id"] = *token.ID
		}
		if token.Name != nil {
			m["name"] = *token.Name
		}
		if token.Type != nil {
			m["type"] = *token.Type
		}
		if token.ApiKeyType != nil {
			m["api_key_type"] = *token.ApiKeyType
		}
		result[i] = m
	}
	return result
}
