package split

import (
	"fmt"
	"log"
	"os"
	"strings"

	splitsdk "github.com/harness/harness-go-sdk/harness/split"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func init() {
	resource.AddTestSweepers("harness_fme_flag_set", &resource.Sweeper{
		Name: "harness_fme_flag_set",
		F:    testSweepFMEFlagSets,
	})
}

// Prefixes match names generated by FME acceptance tests (see internal/service/split/*_test.go).
var fmeSweepFlagSetNamePrefixes = []string{
	"tf_fs_",
	"tf_fs_ds_",
	"tf_drift_",
}

func testSweepFMEFlagSets(_ string) error {
	accountID := os.Getenv("HARNESS_ACCOUNT_ID")
	apiKey := os.Getenv("HARNESS_PLATFORM_API_KEY")
	if accountID == "" || apiKey == "" {
		log.Print("[WARN] Skipping harness_fme_flag_set sweep: HARNESS_ACCOUNT_ID and HARNESS_PLATFORM_API_KEY must be set")
		return nil
	}

	cfg := &splitsdk.Configuration{
		AccountId:     accountID,
		BasePath:      splitsdk.DefaultSplitBasePath,
		ApiKey:        apiKey,
		UserAgent:     "terraform-provider-harness-fme-sweep",
		HTTPClient:    nil,
		DefaultHeader: map[string]string{"X-Api-Key": apiKey},
	}
	client := splitsdk.NewAPIClient(cfg)

	workspaces, err := client.Workspaces.List(nil)
	if err != nil {
		return fmt.Errorf("list Split workspaces: %w", err)
	}

	for _, ws := range workspaces {
		flagSets, err := client.FlagSets.List(ws.ID)
		if err != nil {
			log.Printf("[ERROR] list flag sets workspace %s: %v", ws.ID, err)
			continue
		}
		for _, fs := range flagSets {
			if !fmeFlagSetNameMatchesSweepPrefixes(fs.Name) {
				continue
			}
			if err := client.FlagSets.Delete(fs.ID); err != nil {
				log.Printf("[ERROR] delete flag set %s (%s) in workspace %s: %v", fs.Name, fs.ID, ws.ID, err)
				continue
			}
			log.Printf("[INFO] Deleted FME test flag set %s (%s) in workspace %s", fs.Name, fs.ID, ws.ID)
		}
	}
	return nil
}

func fmeFlagSetNameMatchesSweepPrefixes(name string) bool {
	for _, p := range fmeSweepFlagSetNamePrefixes {
		if strings.HasPrefix(name, p) {
			return true
		}
	}
	return false
}
