/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This contains Input Set details.
type InputSetResponse struct {
	// Account Identifier for the Entity.
	AccountId string `json:"accountId,omitempty"`
	// Organization Identifier for the Entity.
	OrgIdentifier string `json:"orgIdentifier,omitempty"`
	// Project Identifier for the Entity.
	ProjectIdentifier string `json:"projectIdentifier,omitempty"`
	// Pipeline Identifier for the entity.
	PipelineIdentifier string `json:"pipelineIdentifier,omitempty"`
	// Input Set Identifier
	Identifier string `json:"identifier,omitempty"`
	// Input Set YAML
	InputSetYaml string `json:"inputSetYaml,omitempty"`
	// Input Set Name
	Name string `json:"name,omitempty"`
	// Input Set description
	Description string `json:"description,omitempty"`
	// Input Set tags
	Tags map[string]string `json:"tags,omitempty"`
	IsOutdated bool `json:"isOutdated,omitempty"`
	IsErrorResponse bool `json:"isErrorResponse,omitempty"`
	InputSetErrorWrapper *InputSetErrorWrapper `json:"inputSetErrorWrapper,omitempty"`
	GitDetails *PipelineEntityGitDetails `json:"gitDetails,omitempty"`
	EntityValidityDetails *PipelineEntityGitDetails `json:"entityValidityDetails,omitempty"`
	ErrorResponse bool `json:"errorResponse,omitempty"`
	Outdated bool `json:"outdated,omitempty"`
}
