/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StrategyMetadataOrBuilder struct {
	TotalIterations int32 `json:"totalIterations,omitempty"`
	MatrixMetadata *MatrixMetadata `json:"matrixMetadata,omitempty"`
	MatrixMetadataOrBuilder *MatrixMetadataOrBuilder `json:"matrixMetadataOrBuilder,omitempty"`
	MetadataCase string `json:"metadataCase,omitempty"`
	CurrentIteration int32 `json:"currentIteration,omitempty"`
	AllFields map[string]interface{} `json:"allFields,omitempty"`
	DescriptorForType *Descriptor `json:"descriptorForType,omitempty"`
	DefaultInstanceForType *Message `json:"defaultInstanceForType,omitempty"`
	InitializationErrorString string `json:"initializationErrorString,omitempty"`
	UnknownFields *UnknownFieldSet `json:"unknownFields,omitempty"`
	Initialized bool `json:"initialized,omitempty"`
}
