/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the DB Service
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package dbops

type InlineResponse200 struct {
	Image    string            `json:"image,omitempty"`
	Instance *DbInstanceOut    `json:"instance,omitempty"`
	Schema   *DbSchemaOut      `json:"schema,omitempty"`
	Settings map[string]string `json:"settings,omitempty"`
}
