/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type PasswordExpirationPolicy struct {
	Enabled bool `json:"enabled,omitempty"`
	DaysBeforePasswordExpires int32 `json:"daysBeforePasswordExpires,omitempty"`
	DaysBeforeUserNotifiedOfPasswordExpiration int32 `json:"daysBeforeUserNotifiedOfPasswordExpiration,omitempty"`
}
