/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type EnumDescriptorProto struct {
	UnknownFields *UnknownFieldSet `json:"unknownFields,omitempty"`
	Initialized bool `json:"initialized,omitempty"`
	Options *EnumOptions `json:"options,omitempty"`
	SerializedSize int32 `json:"serializedSize,omitempty"`
	ParserForType *ParserEnumDescriptorProto `json:"parserForType,omitempty"`
	DefaultInstanceForType *EnumDescriptorProto `json:"defaultInstanceForType,omitempty"`
	ReservedRangeList []EnumReservedRange `json:"reservedRangeList,omitempty"`
	ReservedNameList []string `json:"reservedNameList,omitempty"`
	OptionsOrBuilder *EnumOptionsOrBuilder `json:"optionsOrBuilder,omitempty"`
	ReservedRangeOrBuilderList []EnumReservedRangeOrBuilder `json:"reservedRangeOrBuilderList,omitempty"`
	ReservedRangeCount int32 `json:"reservedRangeCount,omitempty"`
	ReservedNameCount int32 `json:"reservedNameCount,omitempty"`
	ValueList []EnumValueDescriptorProto `json:"valueList,omitempty"`
	ValueOrBuilderList []EnumValueDescriptorProtoOrBuilder `json:"valueOrBuilderList,omitempty"`
	NameBytes *ByteString `json:"nameBytes,omitempty"`
	ValueCount int32 `json:"valueCount,omitempty"`
	Name string `json:"name,omitempty"`
	AllFields map[string]interface{} `json:"allFields,omitempty"`
	InitializationErrorString string `json:"initializationErrorString,omitempty"`
	DescriptorForType *Descriptor `json:"descriptorForType,omitempty"`
	MemoizedSerializedSize int32 `json:"memoizedSerializedSize,omitempty"`
}
