/*
 * CD NextGen API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * API version: 3.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// This contains Pipeline YAML with the version.
type VariableMergeServiceResponse struct {
	Yaml                            string                              `json:"yaml,omitempty"`
	MetadataMap                     map[string]VariableResponseMapValue `json:"metadataMap,omitempty"`
	ErrorResponses                  []string                            `json:"errorResponses,omitempty"`
	ServiceExpressionPropertiesList []ServiceExpressionProperties       `json:"serviceExpressionPropertiesList,omitempty"`
}
