/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type GithubComHarnessHceSaasGraphqlServerPkgDatabaseMongodbRecommendationNode struct {
	Labels string `json:"labels,omitempty"`
	Name string `json:"name,omitempty"`
}
