/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type Chaoshubv2CreateHubRequest struct {
	ConnectorRef string `json:"connectorRef,omitempty"`
	Description string `json:"description,omitempty"`
	Identity string `json:"identity"`
	Name string `json:"name"`
	RepoBranch string `json:"repoBranch,omitempty"`
	RepoName string `json:"repoName,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
