/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type DatabaseNetworkMapEntity struct {
	Id string `json:"id"`
	Kind *DatabaseNetworkMapResourceKind `json:"kind"`
	Kubernetes *DatabaseNetworkMapEntityKubernetesInfo `json:"kubernetes,omitempty"`
	Name string `json:"name"`
	Removed bool `json:"removed,omitempty"`
	ServiceIdentity *DatabaseServiceIdentity `json:"serviceIdentity,omitempty"`
}
