/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ProbeCmdProbeTemplate struct {
	Command string `json:"command,omitempty"`
	Comparator *ProbeComparatorTemplate `json:"comparator,omitempty"`
	Source string `json:"source,omitempty"`
}
