/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// inputs needed for the Dynatrace probe
type AllOfgithubComHarnessHceSaasHceSdkCommonProbeV1ProbeDynatraceProbeinputs struct {
	// APITokenSecretName for authenticating with the Dynatrace platform
	ApiTokenSecretName string `json:"apiTokenSecretName,omitempty"`
	// Comparator check for the correctness of the probe output
	Comparator *interface{} `json:"comparator,omitempty"`
	// Endpoint of the Dynatrace probe
	Endpoint string `json:"endpoint,omitempty"`
	// Raw metrcis details of the Dynatrace probe
	Metrics *interface{} `json:"metrics,omitempty"`
	// Timeframe of the metrics
	TimeFrame string `json:"timeFrame,omitempty"`
}
