/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type K8sIoApimachineryPkgApisMetaV1ConditionStatus string

// List of k8s_io_apimachinery_pkg_apis_meta_v1.ConditionStatus
const (
	TRUE_K8sIoApimachineryPkgApisMetaV1ConditionStatus K8sIoApimachineryPkgApisMetaV1ConditionStatus = "True"
	FALSE_K8sIoApimachineryPkgApisMetaV1ConditionStatus K8sIoApimachineryPkgApisMetaV1ConditionStatus = "False"
	UNKNOWN_K8sIoApimachineryPkgApisMetaV1ConditionStatus K8sIoApimachineryPkgApisMetaV1ConditionStatus = "Unknown"
)
