/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ProbeApmProbeTemplate struct {
	AppDynamicsProbeInputs *GithubComHarnessHceSaasHceSdkTemplateSchemaProbeAppDynamicsProbeInputs `json:"appDynamicsProbeInputs,omitempty"`
	Comparator *ProbeComparatorTemplate `json:"comparator,omitempty"`
	PrometheusProbeInputs *GithubComHarnessHceSaasHceSdkTemplateSchemaProbePrometheusProbeInputs `json:"prometheusProbeInputs,omitempty"`
	SplunkObservabilityProbeInputs *GithubComHarnessHceSaasHceSdkTemplateSchemaProbeSplunkObservabilityProbeInputs `json:"splunkObservabilityProbeInputs,omitempty"`
	Type_ *ProbeApmProbeType `json:"type,omitempty"`
}
