/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// The source where we have to run the command It will run in inline(inside experiment itself) mode if source is nil
type AllOfv1CmdProbeInputsSource struct {
	// Annotations for the source pod
	Annotations map[string]string `json:"annotations,omitempty"`
	// Args for the source pod
	Args []string `json:"args,omitempty"`
	// Command for the source pod
	Command []string `json:"command,omitempty"`
	// ENVList contains ENV passed to the source pod
	Env []V1EnvVar `json:"env,omitempty"`
	// HostNetwork define the hostNetwork of the external pod it supports boolean values and default value is false
	HostNetwork bool `json:"hostNetwork,omitempty"`
	// Image for the source pod
	Image string `json:"image,omitempty"`
	// ImagePullPolicy for the source pod
	ImagePullPolicy *interface{} `json:"imagePullPolicy,omitempty"`
	// ImagePullSecrets for source pod
	ImagePullSecrets []V1LocalObjectReference `json:"imagePullSecrets,omitempty"`
	// InheritInputs defined to inherit experiment pod attributes(ENV, volumes, and volumeMounts) into probe pod it supports boolean values and default value is false
	InheritInputs bool `json:"inheritInputs,omitempty"`
	// Labels for the source pod
	Labels map[string]string `json:"labels,omitempty"`
	// NodeSelector for the source pod
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// Privileged for the source pod
	Privileged bool `json:"privileged,omitempty"`
	Tolerations []V1Toleration `json:"tolerations,omitempty"`
	// VolumesMount for the source pod
	VolumeMount []V1VolumeMount `json:"volumeMount,omitempty"`
	// Volumes for the source pod
	Volumes []V1Volume `json:"volumes,omitempty"`
}
