/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// FieldsV1 holds the first JSON version format as described in the \"FieldsV1\" type. +optional
type AllOfv1ManagedFieldsEntryFieldsV1 struct {
}
