/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type DatabaseProxyConfiguration struct {
	HttpProxy string `json:"httpProxy,omitempty"`
	HttpsProxy string `json:"httpsProxy,omitempty"`
	// SecretName string `bson:\"secretName\" json:\"secretName\"` CAPath     string `bson:\"caPath\" json:\"caPath\"`
	NoProxy string `json:"noProxy,omitempty"`
	Url string `json:"url,omitempty"`
}
