/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type SecurityGovernanceInfraSpec struct {
	InfraIds []string `json:"infraIds,omitempty"`
	Operator *SecurityGovernanceOperator `json:"operator,omitempty"`
}
