/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ChaosprobetemplateProbeTemplate struct {
	Description string `json:"description,omitempty"`
	HubRef string `json:"hubRef,omitempty"`
	Identity string `json:"identity,omitempty"`
	InfrastructureType *ProbeInfrastructureType `json:"infrastructureType,omitempty"`
	Name string `json:"name"`
	ProbeProperties *ProbeProbeTemplateProperties `json:"probeProperties,omitempty"`
	RunProperties *ProbeProbeTemplateRunProperties `json:"runProperties,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Type_ *ProbeProbeType `json:"type,omitempty"`
	Variables []TemplateVariable `json:"variables,omitempty"`
}
