/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type V1SeccompProfileType string

// List of v1.SeccompProfileType
const (
	UNCONFINED_V1SeccompProfileType V1SeccompProfileType = "Unconfined"
	RUNTIME_DEFAULT_V1SeccompProfileType V1SeccompProfileType = "RuntimeDefault"
	LOCALHOST_V1SeccompProfileType V1SeccompProfileType = "Localhost"
)
