/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type GithubComHarnessHceSaasHceSdkTemplateSchemaProbePost struct {
	Body string `json:"body,omitempty"`
	BodyPath string `json:"bodyPath,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	Criteria string `json:"criteria,omitempty"`
	ResponseBody string `json:"responseBody,omitempty"`
	ResponseCode string `json:"responseCode,omitempty"`
}
