/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ProbeAuthorization struct {
	Credentials string `json:"credentials,omitempty"`
	CredentialsFile string `json:"credentialsFile,omitempty"`
	Type_ string `json:"type,omitempty"`
}
