/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1DownwardApiProjection struct {
	// Items is a list of DownwardAPIVolume file +optional
	Items []V1DownwardApiVolumeFile `json:"items,omitempty"`
}
