/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type InfraV2GetKubernetesInfrastructureV2YamlRequest struct {
	Annotation map[string]string `json:"annotation,omitempty"`
	Containers string `json:"containers,omitempty"`
	CorrelationId string `json:"correlationId,omitempty"`
	Env []InfraV2Env `json:"env,omitempty"`
	EnvironmentID string `json:"environmentID,omitempty"`
	Identifier *InfraV2Identifiers `json:"identifier,omitempty"`
	Identity string `json:"identity,omitempty"`
	InfraNamespace string `json:"infraNamespace,omitempty"`
	InsecureSkipVerify bool `json:"insecureSkipVerify,omitempty"`
	Label map[string]string `json:"label,omitempty"`
	Mtls *InfraV2MtlsConfiguration `json:"mtls,omitempty"`
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	Proxy *InfraV2ProxyConfiguration `json:"proxy,omitempty"`
	RunAsGroup int32 `json:"runAsGroup,omitempty"`
	RunAsUser int32 `json:"runAsUser,omitempty"`
	ServiceAccount string `json:"serviceAccount,omitempty"`
	Tolerations []V1Toleration `json:"tolerations,omitempty"`
	VolumeMounts []V1VolumeMount `json:"volumeMounts,omitempty"`
	Volumes []InfraV2Volumes `json:"volumes,omitempty"`
}
