/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ModelRuleDetails struct {
	Conditions []ModelConditionDetails `json:"conditions,omitempty"`
	Description string `json:"description,omitempty"`
	Message string `json:"message,omitempty"`
	RuleId string `json:"ruleId,omitempty"`
	RuleName string `json:"ruleName,omitempty"`
	TimeWindow *ModelTimeWindow `json:"timeWindow,omitempty"`
	UserGroupIds []string `json:"userGroupIds,omitempty"`
}
