/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type V1K8sProbeInputs struct {
	// Data contains the manifest/data for the resource, which need to be created it supported for create operation only
	Data string `json:"data,omitempty"`
	// fieldselector to get the resource using fields selector
	FieldSelector string `json:"fieldSelector,omitempty"`
	// group of the resource
	Group string `json:"group,omitempty"`
	// labelselector to get the resource using labels selector
	LabelSelector string `json:"labelSelector,omitempty"`
	// namespace of the resource
	Namespace string `json:"namespace,omitempty"`
	// Operation performed by the k8s probe it can be create, delete, present, absent
	Operation string `json:"operation,omitempty"`
	// kind of resource
	Resource string `json:"resource,omitempty"`
	// ResourceNames to get the resources using their list of comma separated names
	ResourceNames string `json:"resourceNames,omitempty"`
	// apiversion of the resource
	Version string `json:"version,omitempty"`
}
