/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type TargetserviceServiceType string

// List of targetservice.ServiceType
const (
	DISCOVERED_SERVICE_TargetserviceServiceType TargetserviceServiceType = "DiscoveredService"
	UN_ACCOUNTED_TargetserviceServiceType TargetserviceServiceType = "UnAccounted"
)
