/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type V2OnboardingAgentData struct {
	ClusterAgent *V2OnboardingAgentDetails `json:"clusterAgent,omitempty"`
	NodeAgent []V2OnboardingAgentDetails `json:"nodeAgent,omitempty"`
}
