/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type K8sfaultK8SFaultSpec struct {
	Chaos *K8sfaultChaosSpec `json:"chaos,omitempty"`
	Target *K8sfaultTarget `json:"target,omitempty"`
}
