/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ModelRecurrenceSpec struct {
	Until int32 `json:"until,omitempty"`
	Value int32 `json:"value,omitempty"`
}
