/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type K8sfaultK8STarget struct {
	Kind string `json:"kind,omitempty"`
	Labels string `json:"labels,omitempty"`
	Names string `json:"names,omitempty"`
	Namespace string `json:"namespace,omitempty"`
}
