/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// AppDynamicsInputs contains the inputs required for AppDynamics probe
type AllOfv1ApmProbeInputsAppDynamicsInputs struct {
	// AppdMetrics contains the appd metrics
	AppdMetrics *interface{} `json:"appdMetrics,omitempty"`
	// AuthSecretName secret name for the authentication
	AuthSecretName string `json:"authSecretName,omitempty"`
	// Endpoint for the AppDynamics probe
	Endpoint string `json:"endpoint,omitempty"`
}
