/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type V1PostMethod struct {
	// Body contains http body for post request
	Body string `json:"body,omitempty"`
	// BodyPath contains filePath, which contains http body
	BodyPath string `json:"bodyPath,omitempty"`
	// ContentType contains content type for http body data
	ContentType string `json:"contentType,omitempty"`
	// Criteria for matching data it supports  == != operations
	Criteria string `json:"criteria,omitempty"`
	// ResponseBody contains the response body for the http post request
	ResponseBody string `json:"responseBody,omitempty"`
	// Value contains relative value for criteria
	ResponseCode string `json:"responseCode,omitempty"`
}
