/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ProbeSloSourceMetadata struct {
	// APITokenSecret for authenticating with the platform service
	ApiTokenSecret string `json:"apiTokenSecret,omitempty"`
	// Scope required for fetching details
	Scope *AllOfprobeSloSourceMetadataScope `json:"scope,omitempty"`
}
