/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ExecutionFaultData struct {
	HelperPodDetails []ExecutionHelperPodDetails `json:"helperPodDetails,omitempty"`
	Name string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	TargetChaosStatus []V1alpha1TargetDetails `json:"targetChaosStatus,omitempty"`
	Targets []V1alpha1Targets `json:"targets,omitempty"`
}
