/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type DatabaseEnvironmentIdentity struct {
	AccountIdentifier string `json:"accountIdentifier,omitempty"`
	Identifier string `json:"identifier,omitempty"`
	InfraIdentifier string `json:"infraIdentifier,omitempty"`
	OrganizationIdentifier string `json:"organizationIdentifier,omitempty"`
	ProjectIdentifier string `json:"projectIdentifier,omitempty"`
}
