/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// Harness identifiers
type AllOfmodelInfrastructureIdentifiers struct {
	// Harness AccountID
	AccountIdentifier string `json:"accountIdentifier,omitempty"`
	// Harness OrgID
	OrgIdentifier string `json:"orgIdentifier,omitempty"`
	// Harness projectID
	ProjectIdentifier string `json:"projectIdentifier,omitempty"`
}
