/*
 * Chaos Manager API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type Gamedayrunv2ApprovalStatus string

// List of gamedayrunv2.ApprovalStatus
const (
	APPROVED_Gamedayrunv2ApprovalStatus Gamedayrunv2ApprovalStatus = "approved"
	REJECTED_Gamedayrunv2ApprovalStatus Gamedayrunv2ApprovalStatus = "rejected"
	PENDING_Gamedayrunv2ApprovalStatus Gamedayrunv2ApprovalStatus = "pending"
)
