---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "harness Provider"
subcategory: ""
description: |-
  For an explanation of how to use this Provider along with code samples, refer to the Harness Terraform Provider Quickstart Guide https://docs.harness.io/article/7cude5tvzh-harness-terraform-provider .
---

# harness Provider



## Example Usage

```terraform
terraform {
  required_providers {
    harness = {
      source = "harness/harness"
    }
  }
}

#Configure the Harness provider for First Gen resources
provider "harness" {
  endpoint   = "https://app.harness.io/gateway"
  account_id = "...."
  api_key    = "......"
}

#Configure the Harness provider for Next Gen resources
provider "harness" {
  endpoint         = "https://app.harness.io/gateway"
  account_id       = "...."
  platform_api_key = "......"
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `account_id` (String) The Harness account id. This can also be set using the `HARNESS_ACCOUNT_ID` environment variable.
- `api_key` (String) The Harness API key. This can also be set using the `HARNESS_API_KEY` environment variable.
- `endpoint` (String) The URL of the Harness API endpoint. The default is `https://app.harness.io/gateway`. This can also be set using the `HARNESS_ENDPOINT` environment variable.
- `platform_api_key` (String) The API key for the Harness next gen platform. This can also be set using the `HARNESS_PLATFORM_API_KEY` environment variable.
