/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package code

type EnumRuleState string

// List of EnumRuleState
const (
	ACTIVE_EnumRuleState   EnumRuleState = "active"
	DISABLED_EnumRuleState EnumRuleState = "disabled"
	MONITOR_EnumRuleState  EnumRuleState = "monitor"
)
