/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package code

type OpenapiCreateBranchRequest struct {
	BypassRules bool   `json:"bypass_rules,omitempty"`
	Name        string `json:"name,omitempty"`
	Target      string `json:"target,omitempty"`
}
