/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package code

type EnumWebhookParent string

// List of EnumWebhookParent
const (
	REPO_EnumWebhookParent  EnumWebhookParent = "repo"
	SPACE_EnumWebhookParent EnumWebhookParent = "space"
)
