/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package code

type OpenapiCreateWebhookRequest struct {
	Description string               `json:"description,omitempty"`
	DisplayName string               `json:"display_name,omitempty"`
	Enabled     bool                 `json:"enabled,omitempty"`
	Identifier  string               `json:"identifier,omitempty"`
	Insecure    bool                 `json:"insecure,omitempty"`
	Secret      string               `json:"secret,omitempty"`
	Triggers    []EnumWebhookTrigger `json:"triggers,omitempty"`
	Uid         string               `json:"uid,omitempty"`
	Url         string               `json:"url,omitempty"`
}
