/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package code

type EnumContentEncodingType string

// List of EnumContentEncodingType
const (
	BASE64_EnumContentEncodingType EnumContentEncodingType = "base64"
	UTF8_EnumContentEncodingType   EnumContentEncodingType = "utf8"
)
