/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package code

type TypesPullReqCheck struct {
	Bypassable bool        `json:"bypassable,omitempty"`
	Check      *TypesCheck `json:"check,omitempty"`
	Required   bool        `json:"required,omitempty"`
}
