/*
 * Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package svcdiscovery

type V1TcpSocketAction struct {
	// Optional: Host name to connect to, defaults to the pod IP. +optional
	Host string `json:"host,omitempty"`
	Port *IntstrIntOrString `json:"port,omitempty"`
}
