/*
 * Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package svcdiscovery

type V1Lifecycle struct {
	PostStart *V1LifecycleHandler `json:"postStart,omitempty"`
	PreStop *V1LifecycleHandler `json:"preStop,omitempty"`
}
