/*
 * Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package svcdiscovery

type DatabaseDataCollectionConfiguration struct {
	BlacklistedNamespaces []string `json:"blacklistedNamespaces,omitempty"`
	CollectionWindowInMin int32 `json:"collectionWindowInMin,omitempty"`
	Cron *DatabaseCronConfig `json:"cron,omitempty"`
	EnableBatchResources bool `json:"enableBatchResources,omitempty"`
	EnableNodeAgent bool `json:"enableNodeAgent,omitempty"`
	EnableOrphanedPod bool `json:"enableOrphanedPod,omitempty"`
	NamespaceSelector string `json:"namespaceSelector,omitempty"`
	NodeAgentSelector string `json:"nodeAgentSelector,omitempty"`
	ObservedNamespaces []string `json:"observedNamespaces,omitempty"`
}
