/*
 * Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package svcdiscovery

type V1DaemonSetUpdateStrategy struct {
	RollingUpdate *V1RollingUpdateDaemonSet `json:"rollingUpdate,omitempty"`
	// Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is RollingUpdate. +optional
	Type_ string `json:"type,omitempty"`
}
