/*
 * Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package svcdiscovery

type V1Affinity struct {
	NodeAffinity *V1NodeAffinity `json:"nodeAffinity,omitempty"`
	PodAffinity *V1PodAffinity `json:"podAffinity,omitempty"`
	PodAntiAffinity *V1PodAntiAffinity `json:"podAntiAffinity,omitempty"`
}
