/*
 * Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package svcdiscovery

type V1DeploymentSpec struct {
	// Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready) +optional
	MinReadySeconds int32 `json:"minReadySeconds,omitempty"`
	// Indicates that the deployment is paused. +optional
	Paused bool `json:"paused,omitempty"`
	// The maximum time in seconds for a deployment to make progress before it is considered to be failed. The deployment controller will continue to process failed deployments and a condition with a ProgressDeadlineExceeded reason will be surfaced in the deployment status. Note that progress will not be estimated during the time a deployment is paused. Defaults to 600s.
	ProgressDeadlineSeconds int32 `json:"progressDeadlineSeconds,omitempty"`
	// Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1. +optional
	Replicas int32 `json:"replicas,omitempty"`
	// The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10. +optional
	RevisionHistoryLimit int32 `json:"revisionHistoryLimit,omitempty"`
	Selector *V1LabelSelector `json:"selector,omitempty"`
	Strategy *V1DeploymentStrategy `json:"strategy,omitempty"`
	Template *V1PodTemplateSpec `json:"template,omitempty"`
}
