/*
 * Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package svcdiscovery

type V1NodeConfigSource struct {
	ConfigMap *V1ConfigMapNodeConfigSource `json:"configMap,omitempty"`
}
